name: eslint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install eslint
      run: npm install eslint
    - name: Analyzing the code with eslint
      run: npx eslint html/script.js
